import Navigation from "@/components/navigation";
import "./globals.scss";
import type { Metadata } from "next";
import StyledComponentsRegistry from "../../lib/AntdRegistry";
import React from "react";
import { getDictionary } from "../../../dictionaries";
import { Locale } from "../../../i18n-config";
import { NextIntlClientProvider } from "next-intl";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const LocaleLayout = async ({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: Locale };
}) => {
  const dict = await getDictionary(locale);

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={dict}>
          <Navigation />
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};
export default LocaleLayout;
